#
# HTTP default passwords go here
#
[[http]]

  [[http.vendors]]
    name = "Cisco"
    auth_type = "basic"
    login_url = "/"

    [[http.vendors.creds]]
      username = "admin"
      password = "cisco"

    [[http.vendors.creds]]
      username = "admin"
      password = "admin"

  [[http.vendors]]
    name = "Mobotix AG"
    auth_type = "basic"
    login_url = "control/userimage.html"

    [[http.vendors.creds]]
      username = "admin"
      password = "meinsm"

  [[http.vendors]]
    name = "Hangzhou Hikvision Digital Technology"
    auth_type = "basic"
    login_url = "/ISAPI/System/status"

    [[http.vendors.creds]]
      username = "admin"
      password = "12345"

  [[http.vendors]]
    name = "Axis Communications AB"
    auth_type = "basic"
    login_url = "/axis-cgi/admin/param.cgi?action=list&group=RemoteService"

    [[http.vendors.creds]]
      username = "root"
      password = "pass"

  [[http.vendors]]
    name = 'Zhejiang Dahua Technology'
    auth_type = "basic"
    login_url = "/axis-cgi/admin/param.cgi?action=list&group=RemoteService"

    [[http.vendors.creds]]
      username = "admin"
      password = "admin"

  [[http.vendors]]
    name = "Panasonic Communications Co"
    auth_type = "basic"
    login_url = '/cgi-bin/main.cgi'

    [[http.vendors.creds]]
      username = 'dispadmin'
      password = '@Panasonic'

  [[http.vendors]]
    name = "Eaton"
    auth_type = "basic"
    login_url = "/set_net.htm"

    [[http.vendors.creds]]
      username = "admin"
      password = "admin"
#
# SSH default creds go here
#
[[ssh]]

  # Uncomment to scan all hosts listening on SSH for a set of default creds
  #[[ssh.vendors]]
  #  name = "Default"
  #  auth_type = "userpass"
  #
  #  [[ssh.vendors.creds]]
  #    username = "root"
  #    password = "toor"

  [[ssh.vendors]]
    name = "Ubiquiti"
    auth_type = "userpass"

    [[ssh.vendors.creds]]
      username = "ubnt"
      password = "ubnt"

  [[ssh.vendors]]
    name = "Raspberry"
    auth_type = "userpass"

    [[ssh.vendors.creds]]
      username = "pi"
      password = "raspberry"

  [[ssh.vendors]]
    name = "Default"
    auth_type = "userpass"

    [[ssh.vendors.creds]]
      username = "podcast"
      password = "podcast"

#
# TELNET default creds go here
#
[[telnet]]

  [[telnet.vendors]]
    name = "Ubiquiti"
    auth_type = "userpass"

    [[telnet.vendors.creds]]
      username = "ubnt"
      password = "ubnt"

  [[telnet.vendors]]
    name = "Netgear"
    auth_type = "userpass"

    [[telnet.vendors.creds]]
      username = "admin"
      password = "password"

  [[telnet.vendors]]
    name = "Cisco"
    auth_type = "userpass"

    [[telnet.vendors.creds]]
      username = "admin"
      password = "admin"
